# Generated by Django 4.2.7 on 2025-11-05 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_leaverequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='requested_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the request was made'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['created_at'], name='join_reques_created_6bb0b6_idx'),
        ),
    ]
