# Generated by Django 4.2.7 on 2025-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_studygroup_studygroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='topics',
            field=models.TextField(blank=True, help_text='Comma-separated list of topics', null=True),
        ),
    ]
