# Generated by Django 4.2.7 on 2025-11-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_studygroup_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('project', 'Project'), ('study_group', 'Study Group')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='projects.studygroup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='projects.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'join_requests',
                'indexes': [models.Index(fields=['requester', 'status'], name='join_reques_request_fc2676_idx'), models.Index(fields=['project', 'status'], name='join_reques_project_16b958_idx'), models.Index(fields=['group', 'status'], name='join_reques_group_i_a85fe3_idx')],
                'unique_together': {('requester', 'group'), ('requester', 'project')},
            },
        ),
    ]
