# Generated by Django 4.2.7 on 2025-11-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_invitation_fields'),
        ('projects', '0007_alter_joinrequest_unique_together_and_more'),
    ]

    operations = [
    ]
