# Generated by Django 4.2.7 on 2025-11-09 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_merge_20251109_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRequest',
            fields=[
                ('invite_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('project', 'Project'), ('study_group', 'Study Group')], editable=False, max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.studygroup')),
                ('invitee', models.ForeignKey(help_text='User who received the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='User who sent the invitation (project/group owner)', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
            ],
            options={
                'db_table': 'invite_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inviter', 'status'], name='invite_requ_inviter_901794_idx'), models.Index(fields=['invitee', 'status'], name='invite_requ_invitee_75fc08_idx'), models.Index(fields=['project', 'status'], name='invite_requ_project_d5ecd0_idx'), models.Index(fields=['group', 'status'], name='invite_requ_group_i_92d07d_idx'), models.Index(fields=['created_at'], name='invite_requ_created_240e17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inviterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('inviter', 'invitee', 'project'), name='unique_project_invitation'),
        ),
        migrations.AddConstraint(
            model_name='inviterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('inviter', 'invitee', 'group'), name='unique_group_invitation'),
        ),
    ]
