# Generated by Django 4.2.7 on 2025-11-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_inviterequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='projects.studygroup'),
        ),
    ]
