# Generated by Django 4.2.7 on 2025-11-10 14:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_leaverequest_project_alter_leaverequest_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inviterequest',
            name='unique_project_invitation',
        ),
        migrations.RemoveConstraint(
            model_name='inviterequest',
            name='unique_group_invitation',
        ),
        migrations.AddConstraint(
            model_name='inviterequest',
            constraint=models.UniqueConstraint(
                fields=('inviter', 'invitee', 'project', 'created_at'),
                condition=models.Q(('project__isnull', False)),
                name='unique_project_invitation'
            ),
        ),
        migrations.AddConstraint(
            model_name='inviterequest',
            constraint=models.UniqueConstraint(
                fields=('inviter', 'invitee', 'group', 'created_at'),
                condition=models.Q(('group__isnull', False)),
                name='unique_group_invitation'
            ),
        ),
    ]