# Generated by Django 4.2.7 on 2025-11-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0011_update_invite_request_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='topics',
        ),
        migrations.CreateModel(
            name='StudyGroupSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
                ('study_group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='projects.studygroup')),
            ],
            options={
                'db_table': 'study_group_skills',
                'unique_together': {('study_group', 'skill')},
            },
        ),
    ]
