# Generated by Django 4.2.7 on 2025-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_studygroup_topics_studygroupskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupskill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
