# Generated by Django 4.2.7

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        # CustomUser model
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='University Serial Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('study_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        
        # Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        
        # Skill model
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Add department field to CustomUser
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
        
        # UserProfile model with CASCADE on delete
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='profile',
                    serialize=False,
                    to=settings.AUTH_USER_MODEL,
                    db_constraint=True,
                )),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        
        # UserSkill model with CASCADE on delete
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='user_skills', 
                    to='accounts.skill'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='user_skills', 
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
        
        # UserAvailability model with CASCADE on delete
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='availability', 
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'User availabilities',
                'ordering': ['day_of_week', 'time_slot_start'],
                'unique_together': {('user', 'day_of_week', 'time_slot_start', 'time_slot_end')},
            },
        ),
        
        # Add database-level CASCADE constraints for all foreign keys
        migrations.RunSQL(
            sql="""
            -- UserProfile CASCADE
            ALTER TABLE accounts_userprofile 
            DROP CONSTRAINT IF EXISTS accounts_userprofile_user_id_92240672_fk_accounts_customuser_usn;
            
            ALTER TABLE accounts_userprofile 
            ADD CONSTRAINT accounts_userprofile_user_id_fk 
            FOREIGN KEY (user_id) 
            REFERENCES accounts_customuser(usn) 
            ON DELETE CASCADE 
            DEFERRABLE INITIALLY DEFERRED;
            
            -- Knox Token CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'knox_authtoken') THEN
                    EXECUTE 'ALTER TABLE knox_authtoken DROP CONSTRAINT IF EXISTS knox_authtoken_user_id_3d8c8d1a_fk_accounts_customuser_usn;';
                    EXECUTE 'ALTER TABLE knox_authtoken ADD CONSTRAINT knox_authtoken_user_id_fk FOREIGN KEY (user_id) REFERENCES accounts_customuser(usn) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- Study Group Members CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'study_group_members') THEN
                    EXECUTE 'ALTER TABLE study_group_members DROP CONSTRAINT IF EXISTS study_group_members_user_id_0c0d509c_fk_accounts_customuser_usn;';
                    EXECUTE 'ALTER TABLE study_group_members ADD CONSTRAINT study_group_members_user_id_fk FOREIGN KEY (user_id) REFERENCES accounts_customuser(usn) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- Join Requests CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'join_requests') THEN
                    -- Requester
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_requester_id_063fab95_fk_accounts_customuser_usn;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_requester_id_fk FOREIGN KEY (requester_id) REFERENCES accounts_customuser(usn) ON DELETE CASCADE;';
                    
                    -- Project
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_project_id_3b8e3281_fk_projects_project_id;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_project_id_fk FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE CASCADE;';
                    
                    -- Group
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_group_id_1bf41b21_fk_study_groups_group_id;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_group_id_fk FOREIGN KEY (group_id) REFERENCES study_groups(group_id) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- Team Members CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'team_members') THEN
                    EXECUTE 'ALTER TABLE team_members DROP CONSTRAINT IF EXISTS team_members_user_id_cfdfac1d_fk_accounts_userprofile_user_id;';
                    EXECUTE 'ALTER TABLE team_members ADD CONSTRAINT team_members_user_id_fk FOREIGN KEY (user_id) REFERENCES accounts_userprofile(user_id) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- Project Skills CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_skills') THEN
                    EXECUTE 'ALTER TABLE project_skills DROP CONSTRAINT IF EXISTS project_skills_project_id_ad92c26a_fk_projects_project_id;';
                    EXECUTE 'ALTER TABLE project_skills ADD CONSTRAINT project_skills_project_id_fk FOREIGN KEY (project_id) REFERENCES projects_project(id) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- Study Group Skills CASCADE (if exists)
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'study_group_skills') THEN
                    EXECUTE 'ALTER TABLE study_group_skills DROP CONSTRAINT IF EXISTS study_group_skills_group_id_6a0c9a7f_fk_study_groups_group_id;';
                    EXECUTE 'ALTER TABLE study_group_skills ADD CONSTRAINT study_group_skills_group_id_fk FOREIGN KEY (group_id) REFERENCES study_groups(group_id) ON DELETE CASCADE;';
                END IF;
            END $$;
            
            -- User Skills CASCADE (already handled in model, but ensuring DB level)
            ALTER TABLE accounts_userskill 
            DROP CONSTRAINT IF EXISTS accounts_userskill_user_id_skill_id_4d5a0f91_uniq;
            
            ALTER TABLE accounts_userskill 
            ADD CONSTRAINT accounts_userskill_user_id_skill_id_uniq 
            UNIQUE (user_id, skill_id);
            
            -- User Availability CASCADE (already handled in model, but ensuring DB level)
            ALTER TABLE accounts_useravailability 
            DROP CONSTRAINT IF EXISTS accounts_useravailability_user_id_day_of_week_time_slot_start_time_slot_end_1c3a7a0b_uniq;
            
            ALTER TABLE accounts_useravailability 
            ADD CONSTRAINT accounts_useravailability_user_id_day_of_week_time_slot_start_time_slot_end_uniq 
            UNIQUE (user_id, day_of_week, time_slot_start, time_slot_end);
            """,
            reverse_sql="""
            -- Revert all constraints to their original state
            -- UserProfile
            ALTER TABLE accounts_userprofile 
            DROP CONSTRAINT IF EXISTS accounts_userprofile_user_id_fk;
            
            ALTER TABLE accounts_userprofile 
            ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_accounts_customuser_usn 
            FOREIGN KEY (user_id) 
            REFERENCES accounts_customuser(usn);
            
            -- Knox Token
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'knox_authtoken') THEN
                    EXECUTE 'ALTER TABLE knox_authtoken DROP CONSTRAINT IF EXISTS knox_authtoken_user_id_fk;';
                    EXECUTE 'ALTER TABLE knox_authtoken ADD CONSTRAINT knox_authtoken_user_id_3d8c8d1a_fk_accounts_customuser_usn FOREIGN KEY (user_id) REFERENCES accounts_customuser(usn);';
                END IF;
            END $$;
            
            -- Study Group Members
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'study_group_members') THEN
                    EXECUTE 'ALTER TABLE study_group_members DROP CONSTRAINT IF EXISTS study_group_members_user_id_fk;';
                    EXECUTE 'ALTER TABLE study_group_members ADD CONSTRAINT study_group_members_user_id_0c0d509c_fk_accounts_customuser_usn FOREIGN KEY (user_id) REFERENCES accounts_customuser(usn);';
                END IF;
            END $$;
            
            -- Join Requests
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'join_requests') THEN
                    -- Requester
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_requester_id_fk;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_requester_id_063fab95_fk_accounts_customuser_usn FOREIGN KEY (requester_id) REFERENCES accounts_customuser(usn);';
                    
                    -- Project
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_project_id_fk;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_project_id_3b8e3281_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES projects_project(id);';
                    
                    -- Group
                    EXECUTE 'ALTER TABLE join_requests DROP CONSTRAINT IF EXISTS join_requests_group_id_fk;';
                    EXECUTE 'ALTER TABLE join_requests ADD CONSTRAINT join_requests_group_id_1bf41b21_fk_study_groups_group_id FOREIGN KEY (group_id) REFERENCES study_groups(group_id);';
                END IF;
            END $$;
            
            -- Team Members
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'team_members') THEN
                    EXECUTE 'ALTER TABLE team_members DROP CONSTRAINT IF EXISTS team_members_user_id_fk;';
                    EXECUTE 'ALTER TABLE team_members ADD CONSTRAINT team_members_user_id_cfdfac1d_fk_accounts_userprofile_user_id FOREIGN KEY (user_id) REFERENCES accounts_userprofile(user_id);';
                END IF;
            END $$;
            
            -- Project Skills
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'project_skills') THEN
                    EXECUTE 'ALTER TABLE project_skills DROP CONSTRAINT IF EXISTS project_skills_project_id_fk;';
                    EXECUTE 'ALTER TABLE project_skills ADD CONSTRAINT project_skills_project_id_ad92c26a_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES projects_project(id);';
                END IF;
            END $$;
            
            -- Study Group Skills
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'study_group_skills') THEN
                    EXECUTE 'ALTER TABLE study_group_skills DROP CONSTRAINT IF EXISTS study_group_skills_group_id_fk;';
                    EXECUTE 'ALTER TABLE study_group_skills ADD CONSTRAINT study_group_skills_group_id_6a0c9a7f_fk_study_groups_group_id FOREIGN KEY (group_id) REFERENCES study_groups(group_id);';
                END IF;
            END $$;
            
            -- User Skills
            ALTER TABLE accounts_userskill 
            DROP CONSTRAINT IF EXISTS accounts_userskill_user_id_skill_id_uniq;
            
            ALTER TABLE accounts_userskill 
            ADD CONSTRAINT accounts_userskill_user_id_skill_id_4d5a0f91_uniq 
            UNIQUE (user_id, skill_id);
            
            -- User Availability
            ALTER TABLE accounts_useravailability 
            DROP CONSTRAINT IF EXISTS accounts_useravailability_user_id_day_of_week_time_slot_start_time_slot_end_uniq;
            
            ALTER TABLE accounts_useravailability 
            ADD CONSTRAINT accounts_useravailability_user_id_day_of_week_time_slot_start_time_slot_end_1c3a7a0b_uniq 
            UNIQUE (user_id, day_of_week, time_slot_start, time_slot_end);
            """,
        ),
    ]
